name: "CI"

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  run-conan:
    strategy:
      matrix:
        compiler: [clang]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - compiler: gcc
          os: ubuntu-latest
        - compiler: msvc
          os: windows-latest


    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Set up Conan profile
      run: |
        conan config install https://github.com/Tsche/github-conan-profiles.git -sf=${{ matrix.os }}

    - name: Build
      working-directory: test
      run: conan build . -s build_type=Debug --build=missing -pr ${{ matrix.compiler }} -pr:b ${{ matrix.compiler }}

    - name: Run
      working-directory: test
      run: ./build/Debug/Foo
